apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-once-daemonset
    app.kubernetes.io/part-of: k8s-once-daemonset
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
