apiVersion: apps.io.huyuan/v1
kind: OnceDaemonSet
metadata:
  name: oncedaemonset-sample
  labels: 
    app: "busybox"
    env: "test"
    version: "0.1.3"
spec:
  restartPolicy: Never
  containers:
  - name: once-daemonset-container
    image: busybox
    command:
    - sh
    - -c
    - sleep 4 


